### ISSUE TITLE
ClassCastException: class org.apache.flink.connector.kafka.sink.KafkaCommittable cannot be cast to class co.decodable.sdk.pipeline.DecodableCommittable 

### ISSUE THREAD

**Issue by gunnarmorling** [decodableco/decodable-pipeline-sdk#30]
Via @rmetzger:

```
java.lang.Exception: Could not perform checkpoint 35 for operator Source: Purchase Orders Source -> Map -> Sink: Writer -> Sink: Committer (1/1)#8.
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointAsyncInMailbox(StreamTask.java:1166)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$triggerCheckpointAsync$12(StreamTask.java:1113)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMail(MailboxProcessor.java:398)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMailsWhenDefaultActionUnavailable(MailboxProcessor.java:367)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:352)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:229)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:831)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:780)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:935)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:914)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:728)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:550)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.flink.runtime.checkpoint.CheckpointException: Could not complete snapshot 35 for operator Source: Purchase Orders Source -> Map -> Sink: Writer -> Sink: Committer (1/1)#8. Failure reason: Checkpoint was declined.
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:269)
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:173)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.snapshotState(AbstractStreamOperator.java:345)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.checkpointStreamOperator(RegularOperatorChain.java:228)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.buildOperatorSnapshotFutures(RegularOperatorChain.java:213)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.snapshotState(RegularOperatorChain.java:192)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.takeSnapshotSync(SubtaskCheckpointCoordinatorImpl.java:726)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:363)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$13(StreamTask.java:1281)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1269)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointAsyncInMailbox(StreamTask.java:1154)
	... 14 more
Caused by: java.lang.ClassCastException: class org.apache.flink.connector.kafka.sink.KafkaCommittable cannot be cast to class co.decodable.sdk.pipeline.DecodableCommittable (org.apache.flink.connector.kafka.sink.KafkaCommittable and co.decodable.sdk.pipeline.DecodableCommittable are in unnamed module of loader org.apache.flink.util.ChildFirstClassLoader @563cd0e6)
	at co.decodable.sdk.pipeline.internal.DelegatingCommittableSerializer.serialize(DelegatingCommittableSerializer.java:14)
	at org.apache.flink.core.io.SimpleVersionedSerialization.writeVersionAndSerialize(SimpleVersionedSerialization.java:59)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer$SubtaskSimpleVersionedSerializer$RequestSimpleVersionedSerializer.serialize(CommittableCollectorSerializer.java:252)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer$SubtaskSimpleVersionedSerializer$RequestSimpleVersionedSerializer.serialize(CommittableCollectorSerializer.java:242)
	at org.apache.flink.core.io.SimpleVersionedSerialization.writeVersionAndSerializeList(SimpleVersionedSerialization.java:91)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer$SubtaskSimpleVersionedSerializer.serialize(CommittableCollectorSerializer.java:214)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer$SubtaskSimpleVersionedSerializer.serialize(CommittableCollectorSerializer.java:182)
	at org.apache.flink.core.io.SimpleVersionedSerialization.writeVersionAndSerializeList(SimpleVersionedSerialization.java:91)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer$CheckpointSimpleVersionedSerializer.serialize(CommittableCollectorSerializer.java:138)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer$CheckpointSimpleVersionedSerializer.serialize(CommittableCollectorSerializer.java:126)
	at org.apache.flink.core.io.SimpleVersionedSerialization.writeVersionAndSerializeList(SimpleVersionedSerialization.java:91)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer.serializeV2(CommittableCollectorSerializer.java:99)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer.serialize(CommittableCollectorSerializer.java:71)
	at org.apache.flink.streaming.runtime.operators.sink.committables.CommittableCollectorSerializer.serialize(CommittableCollectorSerializer.java:43)
	at org.apache.flink.core.io.SimpleVersionedSerialization.writeVersionAndSerialize(SimpleVersionedSerialization.java:174)
	at org.apache.flink.streaming.api.operators.util.SimpleVersionedListState.serialize(SimpleVersionedListState.java:102)
	at org.apache.flink.streaming.api.operators.util.SimpleVersionedListState.serializeAll(SimpleVersionedListState.java:113)
	at org.apache.flink.streaming.api.operators.util.SimpleVersionedListState.update(SimpleVersionedListState.java:71)
	at org.apache.flink.streaming.runtime.operators.sink.CommitterOperator.snapshotState(CommitterOperator.java:129)
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:222)
	... 25 more
```

**Comment by gunnarmorling** [comment]
I think I can get rid of the `DecodableCommittable` and `DecodableWriterState` altogether, and just directly use the Kafka-based counterparts. We should still be able to not surface this at the public API level.
